rails_basics/amazon_cohort42/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get('/',{to: "welcome#home", as: :root})
  get('/about',{to: "welcome#about"})
  get('/contact',{to: "welcome#contact"})
  post("/contact_submit",{to:"welcome#thankyou",as: :contact_submit})
  get("/new_bill",{to:"bills#new_bill"})
  get("/bill", {to: 'bills#result', as: :bill})
  get("/admin/panel", {to: 'welcome#admin'})
  # Labs for rails CRUD
  # get("/products",to:"products#index")
  # get("/products/new",to:"products#new",as: :new_product)
  # post("/products",to:"products#create")

  # get("/products/:id",to:"products#show",as: :product)
  # delete("/products/:id",to:"products#destroy")

  # get("/products/:id/edit",to:"products#edit",as: :edit_product)
  # patch("/products/:id",to:"products#update")

  resources :products do
    resources :reviews, only: [:create, :destroy] do
      resources :likes, shallow: true, only: [:create, :destroy]
      resources :votes, shallow: true, only: [:create, :destroy]
    end
    resources :favourites, shallow: true, only: [:create, :destroy]
  end
  resources :tags, only:[:index]
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :news_articles

  match(
    "/delayed_job",
    to: DelayedJobWeb,
    anchor: false,
    via: [:get, :post]
  )

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :products
      resource :session, only: [:create, :destroy]
      resources :users do
        get :current, on: :collection
      end
    end
  end
end

rails_basics/amazon_cohort42/app/controllers/bills_controller.rb
class BillsController < ApplicationController
    def new_bill
        
    end

    def result
        @amount = params[:amount].to_f
        @tax = params[:tax].to_f
        @tip = params[:tip].to_f
        @number_of_people = params[:number_of_people].to_i
        @total = (@amount*(@tax/100+1)*(@tip/100+1)/@number_of_people).round(2)
    end
    
end

rails_basics/amazon_cohort42/app/helpers/bills_helper.rb
module BillsHelper
end

rails_basics/amazon_cohort42/app/views/bills/new_bill.html.erb
<h1>Bill Splitter</h1>
<%= form_with url: bill_path, method: 'get' do |form|%>
  <div>
    <%= form.label :amount, "Amount:" %>
    <%= form.text_field :amount %>
  </div>
  <div>
    <%= form.label :tax, "Tax:" %>
    <%= form.text_field :tax %>
  </div>
  <div>
     <%= form.label :tip, "Tip:" %>
    <%= form.text_field :tip %>
  </div>
  <div>
    <%= form.label :number_of_people, "Number of people:" %>
    <%= form.text_field :number_of_people %>
  </div>
  <%= form.submit "Submit" %>
<% end %>

rails_basics/amazon_cohort42/app/views/bills/result.html.erb
<br>
Bill Amount is $<%= @amount %> <br>
Tax is <%= @tax %>% <br>
Tip is <%= @tip %>% <br>
<%= @number_of_people %> people <br>
The total per person is <%= @total %>