rails_basics/amazon_cohort42/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get('/',{to: "welcome#home", as: :root})
  get('/about',{to: "welcome#about"})
  get('/contact',{to: "welcome#contact"})
  post("/contact_submit",{to:"welcome#thankyou",as: :contact_submit})
  get("/new_bill",{to:"bills#new_bill"})
  get("/bill", {to: 'bills#result', as: :bill})
  get("/admin/panel", {to: 'welcome#admin'})
  # Labs for rails CRUD
  # get("/products",to:"products#index")
  # get("/products/new",to:"products#new",as: :new_product)
  # post("/products",to:"products#create")

  # get("/products/:id",to:"products#show",as: :product)
  # delete("/products/:id",to:"products#destroy")

  # get("/products/:id/edit",to:"products#edit",as: :edit_product)
  # patch("/products/:id",to:"products#update")

  resources :products do
    resources :reviews, only: [:create, :destroy] do
      resources :likes, shallow: true, only: [:create, :destroy]
      resources :votes, shallow: true, only: [:create, :destroy]
    end
    resources :favourites, shallow: true, only: [:create, :destroy]
  end
  resources :tags, only:[:index]
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :news_articles

  match(
    "/delayed_job",
    to: DelayedJobWeb,
    anchor: false,
    via: [:get, :post]
  )

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :products
      resource :session, only: [:create, :destroy]
      resources :users do
        get :current, on: :collection
      end
    end
  end
end

rails_basics/amazon_cohort42/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmazonCohort42</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <nav>
        <a href="/">Home</a>
        |
        <a href="/about">About</a>
        |
        <a href="/contact">Contact</a>
        |
        <a href="/new_bill">New Bill</a>
        |
        <%= link_to "Products", products_path %>
        |
        <%= link_to "New Product", new_product_path %>
    </nav>
    <br>
    <% flash.each do |type, message|%>
      <%= message%>
    <% end%>
    <% if user_signed_in? %>
    Hello <%= current_user.full_name %>
    <%= link_to "log out", session_path, method: :delete, data:{confirm:"are you sure you want to log out?"} %>
    <% else %>
    <%= link_to "log in", new_session_path %>|
    <%= link_to "sign up", new_user_path %>
    <% end %>
    <%= yield %>
  </body>
</html>