rails_basics/amazon_cohort42/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get('/',{to: "welcome#home", as: :root})
  get('/about',{to: "welcome#about"})
  get('/contact',{to: "welcome#contact"})
  post("/contact_submit",{to:"welcome#thankyou",as: :contact_submit})
  get("/new_bill",{to:"bills#new_bill"})
  get("/bill", {to: 'bills#result', as: :bill})
  get("/admin/panel", {to: 'welcome#admin'})
  # Labs for rails CRUD
  # get("/products",to:"products#index")
  # get("/products/new",to:"products#new",as: :new_product)
  # post("/products",to:"products#create")

  # get("/products/:id",to:"products#show",as: :product)
  # delete("/products/:id",to:"products#destroy")

  # get("/products/:id/edit",to:"products#edit",as: :edit_product)
  # patch("/products/:id",to:"products#update")

  resources :products do
    resources :reviews, only: [:create, :destroy] do
      resources :likes, shallow: true, only: [:create, :destroy]
      resources :votes, shallow: true, only: [:create, :destroy]
    end
    resources :favourites, shallow: true, only: [:create, :destroy]
  end
  resources :tags, only:[:index]
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :news_articles

  match(
    "/delayed_job",
    to: DelayedJobWeb,
    anchor: false,
    via: [:get, :post]
  )

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :products
      resource :session, only: [:create, :destroy]
      resources :users do
        get :current, on: :collection
      end
    end
  end
end

rails_basics/amazon_cohort42/app/models/product.rb
class Product < ApplicationRecord
    after_initialize :set_default_price
    before_save :capitalize_title

    has_many :reviews, dependent: :destroy

    has_many :favourites, dependent: :destroy
    has_many :favouriters, through: :favourites, source: :user
    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings
    belongs_to :user
    validates :title, presence: true, uniqueness: { case_sensitive: false }
    validates :price, numericality:{greater_than: 0}
    validates :description, presence: true, length: { minimum: 10 }

    private
    def set_default_price
        self.price ||= 1
    end

    def capitalize_title
        self.title.capitalize!
    end
end

rails_basics/amazon_cohort42/app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < Api::ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :find_product, only: [:show, :destroy, :update]

    def index
        products = Product.order(created_at: :desc)
        render(json: products)
    end

    def show
        render json: @product
    end

    def create
        product = Product.new product_params
        product.user = current_user
        if product.save
          render json: { id: product.id }
        else
          render(
            json: { errors: product.errors },
            status: 422 
          )
        end
    end

    def destroy
        @product.destroy
        render json: { status: 200 }, status: 200
      end
  
    def update
        if @product.update product_params
          render json: @product
        else
          render(
            json: { errors: @product.errors },
            status: 422 
          )
        end
    end
    
    private
    
    def find_product
      @product ||= Product.find params[:id]
    end

    def product_params
        params.require(:product).permit(:title, :description, :price)
    end
end

rails_basics/amazon_cohort42/app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :find_product, only: [:edit, :update, :show, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    before_action :authorize_user!, only: [:update,:destroy]
    def index
        if params[:tag]
            @tag = Tag.find params[:tag]
            @products = @tag.products
        else
            @products = Product.all 
        end
    end

    def new
        @product = Product.new
    end

    def create
        @product = Product.new product_params
        @product.user = current_user
        if @product.save
            # ProductMailer.new_product(@product).deliver_now
            ProductMailer.new_product(@product).deliver_later
            redirect_to product_path(@product.id)
        else
            render :new
        end
    end

    def show
        @reviews = @product.reviews
        @review = Review.new
        @favourite = Favourite.find_by(product_id: @product, user_id: current_user)
    end

    def destroy
        @product.destroy
        redirect_to products_path
    end

    def edit
    end

    def update
        if @product.update product_params
            redirect_to product_path(@product.id)
        else
            render :edit
        end
    end



    private
    def product_params
        params.require(:product).permit(:title,:description,:price, {tag_ids: []})
    end

    def authorize_user!
        redirect_to root_path, alert: "Not authorized!" unless can?(:crud, @product)
    end
    def find_product
        @product =  Product.find(params[:id])
    end
    
end

rails_basics/amazon_cohort42/app/views/products/_form.html.erb
<% if @product.errors.any? %>
  <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model:@product do |form|%>
<div>
    <%= form.label :title%>
    <%= form.text_field :title%>
</div>
<div>
    <%= form.label :description%>
    <%= form.text_area :description%>
</div>
<div>
    <%= form.label :price%>
    <%= form.text_field :price%>
</div>
<div class="form-group">
    <%= form.collection_check_boxes :tag_ids, Tag.order(name: :asc), :id, :name do |b| %>
        <div class="tag-wrapper">
        <%= b.check_box %>
        <%= b.text.humanize %>
        </div>
    <% end %>
</div>
<div>
    <%= form.submit%>
</div>

<% end %>

rails_basics/amazon_cohort42/app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form' %>

rails_basics/amazon_cohort42/app/views/products/index.html.erb
<h1>All products</h1>

<% @products.each do |product|%>
<div>
    <h2>
    <%= link_to(product.title,product_path(product.id)) %>
    </h2>
</div>
<hr />
<% end %>

rails_basics/amazon_cohort42/app/views/products/new.html.erb
<h1>Create a product</h1>

<%= render 'form' %>

rails_basics/amazon_cohort42/app/views/products/show.html.erb
<h1><%= @product.title%> </h1>
<p><%= @product.description%></p>
<small>$<%= format("%.2f",@product.price)%></small>
<div>

<small>
    <%= link_to("Delete", product_path(@product.id) ,method: :delete, data:{confirm:"Are you sure?"}) %>
</small>
<small>
    <%= link_to("Edit", edit_product_path(@product.id)) %>
</small>
<h5> Created by <%= @product.user.full_name%>
</h5>

<% @product.tags.each do |tag|%>
<%= link_to tag.name, products_path(tag: tag.id), class: "badge badge-pill badge-primary" %>
<% end %>

<% if @favourite%>
  <%= link_to @favourite.is_favourite ? "Cancel Favourite" : "Cancel Unavourite", favourite_path(@favourite), class:"btn btn-light ", method: :delete%>
<% else%>
  <%= form_with(url: product_favourites_path(@product), local: true) do |f| %>
  <input type="hidden" name="is_favourite" value="true">
  <%= f.submit "Favourite", class:"btn btn-info" %>
  <% end %>
  <%= form_with(url: product_favourites_path(@product), local: true) do |f| %>
  <input type="hidden" name="is_favourite" value="false">
  <%= f.submit "Unfavourite", class:"btn btn-dark" %>
  <% end %>
<% end %>
</div> 
<ul>
    <% @reviews.each do |review| %>
        <li>
            <%= review.body %>
            <%= review.rating %>
            <small>
            <%= link_to("Delete", product_review_path(@product.id, review) ,method: :delete, data:{confirm:"Are you sure?"}) %>
            </small>
            <small>
            <% like = review.likes.find_by(user: current_user) %>
            <% if like.present? %>
            <%= link_to "Unlike", like_path(like), method: :delete %>
            <% else %>
            <%= link_to "Like", product_review_likes_path(@product, review), method: :post %>
            <% end%>
            </small>
            <h5> Reviewed by <%= review.user.full_name%>
            </h5>
            |
            <% vote = review.votes.find_by(user: current_user) %>
            <% if vote%>
                <%= link_to vote.is_vote ? "Cancel Vote Up" : "Cancel Vote Down", vote_path(vote), class:"btn btn-light ", method: :delete%>
            <% elsif can?(:vote, review)%>
                <%= form_with(url: product_review_votes_path(@product,review), local: true) do |f| %>
                <input type="hidden" name="is_vote" value="true">
                <%= f.submit "Vote Up", class:"btn btn-info" %>
                <% end %>
                <%= form_with(url: product_review_votes_path(@product,review), local: true) do |f| %>
                <input type="hidden" name="is_vote" value="false">
                <%= f.submit "Vote Down", class:"btn btn-dark" %>
                <% end %>
            <% end %>
            |      
            <small>
                (<%= pluralize(review.votes.where(is_vote: true).count, "vote up") %>)
            </small>
            |      
            <small>
                (<%= pluralize(review.votes.where(is_vote: false).count, "vote down") %>)
            </small>
        </li>
    <% end %>
</ul>

<ul>
<% if @review.errors.any? %>
    <% @review.errors.full_messages.each do |msg|%>
    <li><%= msg %></li>
    <% end %>
<% end %>
</ul>
<%= form_with(model: [@product, @review]) do |form|%>
<div>
    <%= form.label :body%>
    <%= form.text_area :body%>
</div>
<div>
    <%= form.label :rating%>
    <%= form.text_field :rating%>
</div>
<%= form.submit %>
<% end %>